export interface Book {
  id: string;
  title: string;
  author: string;
  category: string;
  summary: string;
  year?: number;
}

export const books: Book[] = [
  // AVONTUUR & FANTASY
  {
    id: "broederband-spookgezichten",
    title: "Broederband: De spookgezichten",
    author: "John Flanagan",
    category: "Avontuur & Fantasy",
    summary: "Na een zware storm spoelen de Reigers aan op een onbekend eiland. Ze moeten een stam beschermen tegen de mysterieuze 'Spookgezichten'.",
    year: 2016,
  },
  {
    id: "grijze-jager-wolven-arazan",
    title: "De grijze jager – De wolven van Arazan",
    author: "John Flanagan",
    category: "Avontuur & Fantasy",
    summary: "Een episch avontuur met de grijze jager in een fantasiewereld vol gevaar en magie.",
    year: 2010,
  },
  {
    id: "stormbreaker",
    title: "Stormbreaker",
    author: "Anthony Horowitz",
    category: "Avontuur & Fantasy",
    summary: "De 14-jarige Alex Rider wordt gerekruteerd door MI6 om na de dood van zijn oom een gevaarlijk complot te onderzoeken.",
    year: 2000,
  },
  {
    id: "helden-van-olympus",
    title: "Helden van Olympus",
    author: "Rick Riordan",
    category: "Avontuur & Fantasy",
    summary: "Een groep halfgoden, zowel Grieks als Romeins, moet samenwerken om de ontwakende oergodin Gaea te stoppen en de wereld te redden.",
    year: 2010,
  },
  {
    id: "verdoemde-zwaard",
    title: "Het verdoemde zwaard",
    author: "Rick Riordan",
    category: "Avontuur & Fantasy",
    summary: "Een spannend avontuur vol mythologische wezens en gevaarlijke quests.",
    year: 2015,
  },
  {
    id: "verloren-bloem-sjamaan",
    title: "De verloren bloem van de sjamaan",
    author: "Davide Morosinotto",
    category: "Avontuur & Fantasy",
    summary: "Laila, de dochter van een Finse diplomaat in Peru, gaat op zoek naar een legendarische geneeskrachtige bloem in het Amazonegebied om haar eigen ziekte te genezen.",
    year: 2020,
  },
  {
    id: "twee-fonkelrode-sterren",
    title: "Twee fonkelrode sterren in de blinkend witte sneeuw",
    author: "Davide Morosinotto",
    category: "Avontuur & Fantasy",
    summary: "Een avontuurlijk verhaal vol sneeuw, magie en ontdekkingen.",
    year: 2018,
  },
  {
    id: "zoon-zee-saga",
    title: "De zoon van de zee: de sage van de familie Da Mar",
    author: "Davide Morosinotto",
    category: "Avontuur & Fantasy",
    summary: "Een epische familiesaga vol zee-avonturen en geheimen.",
    year: 2019,
  },
  {
    id: "twaalf-bevroren-bos",
    title: "Twaalf en het bevroren bos",
    author: "Aisling Fowler",
    category: "Avontuur & Fantasy",
    summary: "Twaalf, een leerling-jager, begint aan een gevaarlijke zoektocht om een ontvoerd meisje uit haar fort te redden.",
    year: 2021,
  },
  {
    id: "vluchteling",
    title: "Vluchteling",
    author: "Alan Gratz",
    category: "Avontuur & Fantasy",
    summary: "Drie verhalen van kinderen (Josef in het Duitsland van de jaren '30, Isabel in Cuba in de jaren '90 en Mahmoud in Syrië in 2015) die vluchten voor gevaar en op zoek zijn naar veiligheid.",
    year: 2016,
  },
  {
    id: "haaieneiland",
    title: "Haaieneiland",
    author: "Rob Ruggenberg",
    category: "Avontuur & Fantasy",
    summary: "Roemer belandt tijdens een 18e-eeuwse expeditie op een gevaarlijk eiland in de Stille Zuidzee, vol haaien en vijandige bewoners.",
    year: 2014,
  },
  {
    id: "skandar-eenhoorndief",
    title: "Skandar en de eenhoorndief",
    author: "A.F. Steadman",
    category: "Avontuur & Fantasy",
    summary: "Skandar droomt ervan een eenhoornrijder te worden, maar eenhoorns zijn gevaarlijke wezens. Hij moet het eiland redden van een duistere vijand.",
    year: 2022,
  },
  {
    id: "verloren-galjoen",
    title: "Het verloren galjoen",
    author: "Johan Vandevelde",
    category: "Avontuur & Fantasy",
    summary: "Lissanda, een weesmeisje met toverkrachten, en Valdemar, een cadet met geheugenverlies, werken samen tijdens een oorlog tussen twee naties.",
    year: 2012,
  },
  {
    id: "apollo",
    title: "Apollo",
    author: "Johan Vandevelde",
    category: "Avontuur & Fantasy",
    summary: "Een spannend avontuur met mythologische elementen.",
    year: 2013,
  },
  {
    id: "nachtwild",
    title: "Nachtwild",
    author: "Johan Vandevelde",
    category: "Avontuur & Fantasy",
    summary: "Een mysterieus avontuur in de nacht vol geheimen.",
    year: 2014,
  },
  {
    id: "lampje",
    title: "Lampje",
    author: "Annet Schaap",
    category: "Avontuur & Fantasy",
    summary: "Lampje, de dochter van een vuurtorenwachter, veroorzaakt per ongeluk een schipbreuk en beleeft daarna avonturen in een mysterieus huis.",
    year: 2016,
  },
  {
    id: "als-sterren-zingen",
    title: "Als de sterren zingen",
    author: "Tonke Dragt",
    category: "Avontuur & Fantasy",
    summary: "Een klassiek avontuursverhaal vol spanning en magie.",
    year: 2002,
  },
  {
    id: "school-goed-kwaad",
    title: "De school van goed en kwaad",
    author: "Soman Chainani",
    category: "Avontuur & Fantasy",
    summary: "Een magische school waar goed en kwaad tegen elkaar strijden.",
    year: 2013,
  },
  {
    id: "zilvergaren",
    title: "Zilvergaren",
    author: "Naomi Novik",
    category: "Avontuur & Fantasy",
    summary: "Een magisch avontuur vol betovering en gevaar.",
    year: 2015,
  },
  {
    id: "stad-vol-geesten",
    title: "Stad vol geesten",
    author: "V.E. Schwab",
    category: "Avontuur & Fantasy",
    summary: "Een donkere fantasiestad vol geheimen en magie.",
    year: 2014,
  },
  {
    id: "wonderlingen",
    title: "De Wonderlingen",
    author: "Brian Selznick",
    category: "Avontuur & Fantasy",
    summary: "Een visueel avontuur vol illustraties en mysterie.",
    year: 2014,
  },
  {
    id: "maresi",
    title: "Maresi",
    author: "Maria Turtschaninoff",
    category: "Avontuur & Fantasy",
    summary: "Een meisje ontdekt een verborgen eiland vol magie en geheimen.",
    year: 2014,
  },
  {
    id: "erebos-ontwaakt",
    title: "Erebos ontwaakt",
    author: "Ursula Poznanski",
    category: "Avontuur & Fantasy",
    summary: "Een mysterieus computerspel met gevaarlijke gevolgen.",
    year: 2012,
  },
  {
    id: "beest-kracht-tien-paarden",
    title: "Het beest met de kracht van tien paarden",
    author: "Lida Dijkstra",
    category: "Avontuur & Fantasy",
    summary: "Een episch verhaal met een legendarisch beest.",
    year: 2010,
  },
  {
    id: "jongen-berg",
    title: "De jongen op de berg",
    author: "John Boyne",
    category: "Avontuur & Fantasy",
    summary: "Een jongen ontdekt geheimen op een mysterieuze berg.",
    year: 2015,
  },
  {
    id: "wereld-achter-hek",
    title: "De wereld achter het hek",
    author: "Zana Fraillon",
    category: "Avontuur & Fantasy",
    summary: "Een avontuur in een verborgen wereld vol wonderen.",
    year: 2016,
  },

  // MYSTERIE & THRILLER
  {
    id: "geschiedenis-jane-doe",
    title: "De geschiedenis van Jane Doe",
    author: "Michael Belanger",
    category: "Mysterie & Thriller",
    summary: "Een meisje zonder geheugen probeert haar identiteit te achterhalen.",
    year: 2014,
  },
  {
    id: "vermoord-verleden",
    title: "Vermoord het verleden",
    author: "Jonas Boets",
    category: "Mysterie & Thriller",
    summary: "Een thriller over het onthullen van geheimen uit het verleden.",
    year: 2012,
  },
  {
    id: "clash",
    title: "Clash",
    author: "Guy Didelez",
    category: "Mysterie & Thriller",
    summary: "Een spannende thriller vol onverwachte wendingen.",
    year: 2014,
  },
  {
    id: "onbreekbaar",
    title: "(On)breekbaar",
    author: "Guy Didelez",
    category: "Mysterie & Thriller",
    summary: "Een mysterie over fragiele relaties en geheimen.",
    year: 2013,
  },
  {
    id: "raspoetin",
    title: "Raspoetin",
    author: "Guy Didelez",
    category: "Mysterie & Thriller",
    summary: "Een historische thriller over de mysterieuze Raspoetin.",
    year: 2011,
  },
  {
    id: "eeuwig-zwijgen",
    title: "Eeuwig zwijgen",
    author: "Guy Didelez",
    category: "Mysterie & Thriller",
    summary: "Een donkere thriller vol geheimen die niet verteld mogen worden.",
    year: 2010,
  },
  {
    id: "maan-zaak",
    title: "De maan-zaak",
    author: "Stuart Gibbs",
    category: "Mysterie & Thriller",
    summary: "Een mysterie op de maan vol onverwachte wendingen.",
    year: 2014,
  },
  {
    id: "wonderbaarlijke-voorval-hond",
    title: "Het wonderbaarlijke voorval met de hond in de nacht",
    author: "Mark Haddon",
    category: "Mysterie & Thriller",
    summary: "Een jongen met autisme onderzoekt de dood van een hond.",
    year: 2003,
  },
  {
    id: "brieven-duisternis",
    title: "Brieven aan de duisternis",
    author: "Brigid Kemmerer",
    category: "Mysterie & Thriller",
    summary: "Een thriller over geheime brieven en gevaarlijke waarschijnlijkheden.",
    year: 2014,
  },
  {
    id: "bloedgevaar",
    title: "Bloedgevaar",
    author: "Kate Kriske",
    category: "Mysterie & Thriller",
    summary: "Een thriller vol spanning en gevaar.",
    year: 2012,
  },
  {
    id: "offer-baobab",
    title: "Het offer van de Baobab",
    author: "Kate Kriske",
    category: "Mysterie & Thriller",
    summary: "Een mysterie in Afrika vol geheimen.",
    year: 2013,
  },
  {
    id: "body-switch",
    title: "Body Switch",
    author: "Patrick Lagrou",
    category: "Mysterie & Thriller",
    summary: "Een thriller over lichaamsverwisseling en identiteit.",
    year: 2014,
  },
  {
    id: "jacht",
    title: "Jacht",
    author: "Cis Meijer",
    category: "Mysterie & Thriller",
    summary: "Een spannende jacht op een gevaarlijke vijand.",
    year: 2013,
  },
  {
    id: "blackmail",
    title: "Blackmail",
    author: "Cis Meijer",
    category: "Mysterie & Thriller",
    summary: "Een thriller over chantage en geheimen.",
    year: 2014,
  },
  {
    id: "raven",
    title: "De raven",
    author: "Kass Morgan",
    category: "Mysterie & Thriller",
    summary: "Een donkere thriller vol mysterie en gevaar.",
    year: 2015,
  },
  {
    id: "project-z",
    title: "Project Z",
    author: "Marloes Morshuis",
    category: "Mysterie & Thriller",
    summary: "Een thriller over een geheim project met gevaarlijke gevolgen.",
    year: 2015,
  },
  {
    id: "schaduwen-radovar",
    title: "De schaduwen van Radovar",
    author: "Marloes Morshuis",
    category: "Mysterie & Thriller",
    summary: "Een mysterie in een donkere stad vol geheimen.",
    year: 2016,
  },
  {
    id: "boy-7",
    title: "Boy 7",
    author: "Mirjam Mous",
    category: "Mysterie & Thriller",
    summary: "Een jongen zonder geheugen probeert zijn verleden te achterhalen.",
    year: 2015,
  },
  {
    id: "girl-6",
    title: "Girl 6",
    author: "Mirjam Mous",
    category: "Mysterie & Thriller",
    summary: "Een meisje ontdekt een gevaarlijk geheim.",
    year: 2016,
  },
  {
    id: "2c",
    title: "2C",
    author: "Mirjam Mous",
    category: "Mysterie & Thriller",
    summary: "Een thriller over een klas vol geheimen.",
    year: 2017,
  },
  {
    id: "als-je-dit-leest-ben-ik-dood",
    title: "Als je dit leest, ben ik dood",
    author: "Sally Nicholls",
    category: "Mysterie & Thriller",
    summary: "Een meisje schrijft brieven voordat ze sterft.",
    year: 2012,
  },
  {
    id: "om-nooit-vergeten",
    title: "Om nooit te vergeten",
    author: "Thomas Olde Heuvelt",
    category: "Mysterie & Thriller",
    summary: "Een thriller over een dorp met een donker geheim.",
    year: 2014,
  },
  {
    id: "dodenhuis",
    title: "Het dodenhuis",
    author: "Sarah Pinborough",
    category: "Mysterie & Thriller",
    summary: "Een horror-thriller in een oud huis vol geesten.",
    year: 2012,
  },
  {
    id: "13-minuten",
    title: "13 minuten",
    author: "Sarah Pinborough",
    category: "Mysterie & Thriller",
    summary: "Een meisje sterft en niemand weet waarom.",
    year: 2014,
  },
  {
    id: "heartstream",
    title: "Heartstream",
    author: "Tom Pollock",
    category: "Mysterie & Thriller",
    summary: "Een thriller over een geheimzinnig netwerk.",
    year: 2012,
  },
  {
    id: "duizend-geheimen-complot",
    title: "Het duizend geheimen complot",
    author: "Janet Sumner Johnson",
    category: "Mysterie & Thriller",
    summary: "Een thriller over een geheim complot.",
    year: 2015,
  },
  {
    id: "tunnel",
    title: "De Tunnel",
    author: "Anna Woltz",
    category: "Mysterie & Thriller",
    summary: "Een thriller over een geheime tunnel vol geheimen.",
    year: 2013,
  },
  {
    id: "gips",
    title: "Gips",
    author: "Anna Woltz",
    category: "Mysterie & Thriller",
    summary: "Een meisje in gips ontdekt een groot geheim.",
    year: 2014,
  },

  // LIEFDE & RELATIES
  {
    id: "vervloekt",
    title: "Vervloekt",
    author: "Josephine Angelini",
    category: "Liefde & Relaties",
    summary: "Een liefdesverhaal vol magie en vervloekingen.",
    year: 2011,
  },
  {
    id: "episch-liefdesverhaal",
    title: "Dit is best wel een episch liefdesverhaal",
    author: "Karen Callender",
    category: "Liefde & Relaties",
    summary: "Een grappig en romantisch verhaal over eerste liefde.",
    year: 2015,
  },
  {
    id: "blauwe-dagen",
    title: "Blauwe dagen",
    author: "Caja Cazemier",
    category: "Liefde & Relaties",
    summary: "Een verhaal over liefde en verdriet.",
    year: 2010,
  },
  {
    id: "geen-saldo",
    title: "Geen saldo",
    author: "Caja Cazemier",
    category: "Liefde & Relaties",
    summary: "Een meisje verliest alles en moet opnieuw beginnen.",
    year: 2011,
  },
  {
    id: "like-me",
    title: "Like me!",
    author: "Caja Cazemier",
    category: "Liefde & Relaties",
    summary: "Een verhaal over sociale media en identiteit.",
    year: 2014,
  },
  {
    id: "gewicht-water",
    title: "Gewicht van water",
    author: "Sarah Crossan",
    category: "Liefde & Relaties",
    summary: "Een verhaal over vriendschap en eerste liefde.",
    year: 2012,
  },
  {
    id: "spiegel",
    title: "Spiegel",
    author: "Cara Delevingne",
    category: "Liefde & Relaties",
    summary: "Een meisje ontdekt haar ware zelf.",
    year: 2014,
  },
  {
    id: "neem-mijn-hand",
    title: "Neem mijn hand",
    author: "Kate DiCamillo",
    category: "Liefde & Relaties",
    summary: "Een verhaal over liefde en hoop.",
    year: 2008,
  },
  {
    id: "omdat-ik-niet-wou-kussen",
    title: "Omdat ik niet wou kussen",
    author: "Guy Didelez",
    category: "Liefde & Relaties",
    summary: "Een meisje weigert te kussen en ontdekt waarom.",
    year: 2010,
  },
  {
    id: "molokai-tocht",
    title: "Molokai, de tocht van beeldschoon en lieveling",
    author: "Guy Didelez",
    category: "Liefde & Relaties",
    summary: "Een liefdesverhaal op een eiland.",
    year: 2012,
  },
  {
    id: "ik-moet-dit-doen",
    title: "Ik moet dit doen",
    author: "Maren Stoffels",
    category: "Liefde & Relaties",
    summary: "Een meisje moet een belangrijke beslissing nemen.",
    year: 2014,
  },
  {
    id: "nog-27-dagen-leven",
    title: "Nog 27 dagen leven",
    author: "Maren Stoffels",
    category: "Liefde & Relaties",
    summary: "Een meisje heeft nog maar 27 dagen te leven.",
    year: 2015,
  },
  {
    id: "cinder-ella",
    title: "Cinder & Ella",
    author: "Kelly Oram",
    category: "Liefde & Relaties",
    summary: "Een moderne versie van Assepoester.",
    year: 2013,
  },
  {
    id: "voorbestemd",
    title: "Voorbestemd: iedereen heeft iets nodig om in te geloven",
    author: "Alice Oseman",
    category: "Liefde & Relaties",
    summary: "Een verhaal over geloof en liefde.",
    year: 2015,
  },
  {
    id: "romeo-julia",
    title: "Romeo & Julia",
    author: "Tiny Fisscher",
    category: "Liefde & Relaties",
    summary: "Een moderne versie van Shakespeares klassieker.",
    year: 2012,
  },
  {
    id: "voor-altijd-romeo-julia",
    title: "Voor altijd: Romeo en Julia: een vleselijk liefdesverhaal",
    author: "Pepijn Lievens",
    category: "Liefde & Relaties",
    summary: "Een volwassen versie van Romeo en Julia.",
    year: 2013,
  },
  {
    id: "weeffout-sterren",
    title: "Een weeffout in onze sterren",
    author: "John Green",
    category: "Liefde & Relaties",
    summary: "Twee tieners met kanker ontmoeten elkaar en verlieven zich.",
    year: 2012,
  },
  {
    id: "schildpadden-oneindige",
    title: "Schildpadden tot in het oneindige",
    author: "John Green",
    category: "Liefde & Relaties",
    summary: "Een meisje probeert een mysterie op te lossen.",
    year: 2008,
  },
  {
    id: "darius-grote",
    title: "Darius de Grote",
    author: "Adib Khorram",
    category: "Liefde & Relaties",
    summary: "Een Iraanse jongen ontdekt zichzelf en de liefde.",
    year: 2018,
  },
  {
    id: "lied-alleen-ik-horen",
    title: "Een lied dat alleen ik kan horen",
    author: "Barry Jonsberg",
    category: "Liefde & Relaties",
    summary: "Een jongen hoort muziek die niemand anders kan horen.",
    year: 2012,
  },
  {
    id: "hallo-nu",
    title: "Hallo nu",
    author: "Jenny Valentine",
    category: "Liefde & Relaties",
    summary: "Een meisje ontmoet een jongen en alles verandert.",
    year: 2012,
  },
  {
    id: "dansen-beginners",
    title: "Dansen voor beginners",
    author: "Nicola Yoon",
    category: "Liefde & Relaties",
    summary: "Een meisje leert dansen en ontdekt de liefde.",
    year: 2015,
  },
  {
    id: "alles-wat-je-lief-is",
    title: "Alles wat je lief is",
    author: "Nicola Yoon",
    category: "Liefde & Relaties",
    summary: "Een verhaal over alles wat we liefhebben.",
    year: 2016,
  },

  // DRAMA & REALISME
  {
    id: "onverklaarbare-logica",
    title: "De onverklaarbare logica van mijn leven",
    author: "Benjamin Alire Saenz",
    category: "Drama & Realisme",
    summary: "Een Mexicaans-Amerikaanse jongen zoekt zijn plaats in de wereld.",
    year: 2012,
  },
  {
    id: "meisje-india-fietste",
    title: "Het meisje dat door India fietste",
    author: "André Aletta",
    category: "Drama & Realisme",
    summary: "Een meisje fietst door India en ontdekt zichzelf.",
    year: 2010,
  },
  {
    id: "hart-adelaar",
    title: "Het hart van de adelaar",
    author: "Emmelie Arents",
    category: "Drama & Realisme",
    summary: "Een verhaal over moed en zelfontdekking.",
    year: 2014,
  },
  {
    id: "geheugenboek",
    title: "Het geheugenboek",
    author: "Lara Avery",
    category: "Drama & Realisme",
    summary: "Een meisje schrijft haar herinneringen op voordat ze sterft.",
    year: 2016,
  },
  {
    id: "condor",
    title: "Condor",
    author: "Baele / Claes",
    category: "Drama & Realisme",
    summary: "Een verhaal over vrijheid en grenzen.",
    year: 2013,
  },
  {
    id: "huis-zonder-einde",
    title: "Huis zonder einde",
    author: "Daniëlle Bakhuis",
    category: "Drama & Realisme",
    summary: "Een meisje ontdekt geheimen in haar huis.",
    year: 2014,
  },
  {
    id: "iron-sisters",
    title: "The Iron sisters",
    author: "Tracy Banghart",
    category: "Drama & Realisme",
    summary: "Twee zussen vinden hun kracht.",
    year: 2014,
  },
  {
    id: "zomer-parijs-bestormden",
    title: "De zomer dat we Parijs bestormden",
    author: "Clémentine Beauvais",
    category: "Drama & Realisme",
    summary: "Drie meisjes beleven een avontuurlijke zomer in Parijs.",
    year: 2014,
  },
  {
    id: "helletorens",
    title: "De helletorens",
    author: "Hannelore Bedert",
    category: "Drama & Realisme",
    summary: "Een verhaal over angst en overwinning.",
    year: 2012,
  },
  {
    id: "een-mens-genoeg",
    title: "Eén mens is genoeg",
    author: "Els Beerten",
    category: "Drama & Realisme",
    summary: "Een verhaal over liefde en verlies.",
    year: 2013,
  },
  {
    id: "ik-ken-jouw-geheim",
    title: "Ik ken jouw geheim",
    author: "Daphne Benedis-Grab",
    category: "Drama & Realisme",
    summary: "Een meisje ontdekt geheimen van anderen.",
    year: 2015,
  },
  {
    id: "zoeken-paulie-fink",
    title: "Op zoek naar Paulie Fink",
    author: "Ali Benjamin",
    category: "Drama & Realisme",
    summary: "Een meisje zoekt naar een vermiste jongen.",
    year: 2014,
  },
  {
    id: "suzy-kwallen",
    title: "Suzy en de kwallen",
    author: "Ali Benjamin / Terry Fan",
    category: "Drama & Realisme",
    summary: "Een verhaal over vriendschap en zee.",
    year: 2015,
  },
  {
    id: "onderbuik",
    title: "Onderbuik",
    author: "Tine Bergen",
    category: "Drama & Realisme",
    summary: "Een meisje worstelt met haar lichaam en identiteit.",
    year: 2015,
  },
  {
    id: "buitenspel-boets",
    title: "Buitenspel",
    author: "Jonas Boets",
    category: "Drama & Realisme",
    summary: "Een voetballer verliest alles.",
    year: 2011,
  },
  {
    id: "geboren-scoren",
    title: "Geboren om te scoren",
    author: "Jonas Boets",
    category: "Drama & Realisme",
    summary: "Een jongen wil voetballer worden.",
    year: 2012,
  },
  {
    id: "liever-leugen",
    title: "Liever de leugen",
    author: "Jonas Boets",
    category: "Drama & Realisme",
    summary: "Een jongen kiest voor de leugen.",
    year: 2013,
  },
  {
    id: "vogelkinderen",
    title: "Vogelkinderen",
    author: "Mark Boode",
    category: "Drama & Realisme",
    summary: "Kinderen zonder ouders zoeken hun weg.",
    year: 2014,
  },
  {
    id: "dit-hoe-ging",
    title: "Dit is hoe het ging",
    author: "Astrid Boonstoppel",
    category: "Drama & Realisme",
    summary: "Een verhaal over hoe alles verandert.",
    year: 2015,
  },
  {
    id: "broer-jessica",
    title: "Mijn broer heet Jessica",
    author: "John Boyne",
    category: "Drama & Realisme",
    summary: "Een broer accepteert dat zijn zus transgender is.",
    year: 2014,
  },
  {
    id: "blauw-bitter",
    title: "Blauw is bitter",
    author: "Dirk Bracke",
    category: "Drama & Realisme",
    summary: "Een verhaal over depressie en hoop.",
    year: 2012,
  },
  {
    id: "black",
    title: "Black",
    author: "Dirk Bracke",
    category: "Drama & Realisme",
    summary: "Een donker verhaal over duisternis.",
    year: 2013,
  },
  {
    id: "monster-groene-ogen",
    title: "Het monster met de groene ogen",
    author: "Jo Claes",
    category: "Drama & Realisme",
    summary: "Een verhaal over jaloezie en vriendschap.",
    year: 2012,
  },
  {
    id: "eindspel",
    title: "Eindspel",
    author: "Evy Danckers",
    category: "Drama & Realisme",
    summary: "Een schaakspeler bereikt het eindspel van zijn leven.",
    year: 2014,
  },
  {
    id: "dorp-zwaluwen",
    title: "Het dorp van de zwaluwen",
    author: "Marc De Bel",
    category: "Drama & Realisme",
    summary: "Een verhaal over een dorp vol geheimen.",
    year: 2013,
  },
  {
    id: "mette",
    title: "Mette",
    author: "Marc De Bel",
    category: "Drama & Realisme",
    summary: "Een meisje ontdekt wie ze werkelijk is.",
    year: 2014,
  },
  {
    id: "nelle-blankgoud",
    title: "Nelle, blankgoud",
    author: "Marc De Bel",
    category: "Drama & Realisme",
    summary: "Een verhaal over schoonheid en waarheid.",
    year: 2015,
  },
  {
    id: "nelle-heks-kruisem",
    title: "Nelle, de heks van Kruisem",
    author: "Marc De Bel",
    category: "Drama & Realisme",
    summary: "Een meisje wordt beschuldigd van hekserij.",
    year: 2016,
  },
  {
    id: "tsunami",
    title: "Tsunami",
    author: "Nico De Braeckeleer",
    category: "Drama & Realisme",
    summary: "Een verhaal over een natuurramp en overleven.",
    year: 2012,
  },
  {
    id: "ziel",
    title: "Ziel",
    author: "Nico De Braeckeleer",
    category: "Drama & Realisme",
    summary: "Een verhaal over de ziel en het bestaan.",
    year: 2013,
  },
  {
    id: "lily",
    title: "Lily",
    author: "Tom De Cock",
    category: "Drama & Realisme",
    summary: "Een verhaal over liefde en verlies.",
    year: 2014,
  },
  {
    id: "cello-mevrouw-rozas",
    title: "De cello van mevrouw Rozas",
    author: "Piet De Loof",
    category: "Drama & Realisme",
    summary: "Een verhaal over muziek en herinnering.",
    year: 2013,
  },
  {
    id: "broer-demesmaeker",
    title: "+broer",
    author: "Mario Demesmaeker",
    category: "Drama & Realisme",
    summary: "Een jongen krijgt een nieuwe broer.",
    year: 2014,
  },
  {
    id: "eilanden-profetie",
    title: "Eilanden: de profetie",
    author: "Luc Descamps",
    category: "Drama & Realisme",
    summary: "Een verhaal over eilanden en voorspellingen.",
    year: 2012,
  },
  {
    id: "gewoon-anders",
    title: "[gewoon] Anders",
    author: "Luc Descamps",
    category: "Drama & Realisme",
    summary: "Een verhaal over anders zijn.",
    year: 2013,
  },
  {
    id: "gewoon-gevoelig",
    title: "[gewoon] Gevoelig",
    author: "Luc Descamps",
    category: "Drama & Realisme",
    summary: "Een verhaal over gevoeligheid.",
    year: 2013,
  },
  {
    id: "gewoon-kwetsbaar",
    title: "[gewoon] Kwetsbaar",
    author: "Luc Descamps",
    category: "Drama & Realisme",
    summary: "Een verhaal over kwetsbaarheid.",
    year: 2013,
  },
  {
    id: "gewoon-leven",
    title: "[gewoon] Leven",
    author: "Luc Descamps",
    category: "Drama & Realisme",
    summary: "Een verhaal over het leven.",
    year: 2013,
  },
  {
    id: "gewoon-mezelf",
    title: "[gewoon] Mezelf",
    author: "Luc Descamps",
    category: "Drama & Realisme",
    summary: "Een verhaal over jezelf zijn.",
    year: 2013,
  },
  {
    id: "gewoon-verliefd",
    title: "[gewoon] Verliefd",
    author: "Luc Descamps",
    category: "Drama & Realisme",
    summary: "Een verhaal over verliefd zijn.",
    year: 2013,
  },
  {
    id: "en-ik-dan",
    title: "En ik dan?",
    author: "Luc Descamps",
    category: "Drama & Realisme",
    summary: "Een verhaal over jezelf stellen.",
    year: 2014,
  },
  {
    id: "duivelskruid",
    title: "Duivelskruid",
    author: "Marita De Sterck",
    category: "Drama & Realisme",
    summary: "Een verhaal over duivelse verleidingen.",
    year: 2012,
  },
  {
    id: "zoethout",
    title: "Zoethout",
    author: "Marita De Sterck",
    category: "Drama & Realisme",
    summary: "Een verhaal over zoete dingen.",
    year: 2013,
  },
  {
    id: "wish-you-were-here",
    title: "Wish you were here",
    author: "Evelien De Vlieger",
    category: "Drama & Realisme",
    summary: "Een verhaal over afwezigheid en verlangen.",
    year: 2014,
  },
  {
    id: "vals",
    title: "Vals",
    author: "Mel Wallis De Vries",
    category: "Drama & Realisme",
    summary: "Een verhaal over valse identiteiten.",
    year: 2012,
  },
  {
    id: "shock",
    title: "Shock",
    author: "Mel Wallis De Vries",
    category: "Drama & Realisme",
    summary: "Een verhaal over schokken.",
    year: 2013,
  },
  {
    id: "wreed",
    title: "Wreed",
    author: "Mel Wallis De Vries",
    category: "Drama & Realisme",
    summary: "Een verhaal over wreedheid.",
    year: 2013,
  },
  {
    id: "klem",
    title: "Klem",
    author: "Mel Wallis De Vries",
    category: "Drama & Realisme",
    summary: "Een verhaal over vastzitten.",
    year: 2014,
  },
  {
    id: "schuld",
    title: "Schuld",
    author: "Mel Wallis De Vries",
    category: "Drama & Realisme",
    summary: "Een verhaal over schuld en verantwoordelijkheid.",
    year: 2014,
  },
  {
    id: "exit",
    title: "Exit",
    author: "Mel Wallis De Vries",
    category: "Drama & Realisme",
    summary: "Een verhaal over uitwegen.",
    year: 2015,
  },
  {
    id: "lied-vreemdeling",
    title: "Het lied van de vreemdeling",
    author: "Linda Dielemans",
    category: "Drama & Realisme",
    summary: "Een verhaal over vreemdelingen en muziek.",
    year: 2013,
  },
  {
    id: "halve-helden",
    title: "Halve helden",
    author: "Karen Dierickx",
    category: "Drama & Realisme",
    summary: "Een verhaal over onvolmaakte helden.",
    year: 2014,
  },
  {
    id: "stiefzus",
    title: "Stiefzus: schoonheid is niet altijd mooi",
    author: "Jennifer Donnelly",
    category: "Drama & Realisme",
    summary: "Een meisje leert wat echte schoonheid is.",
    year: 2012,
  },
  {
    id: "wolfskinderen",
    title: "Wolfskinderen",
    author: "Paul Dowswell",
    category: "Drama & Realisme",
    summary: "Kinderen die als wolven opgroeien.",
    year: 2011,
  },
  {
    id: "in-mijn-hoofd",
    title: "In mijn hoofd",
    author: "Sharon M. Draper",
    category: "Drama & Realisme",
    summary: "Een meisje kan niet spreken maar denkt veel.",
    year: 2010,
  },
  {
    id: "stukjes-hemelblauw",
    title: "Stukjes Hemelblauw",
    author: "Sue Durrant",
    category: "Drama & Realisme",
    summary: "Een verhaal over stukjes geluk.",
    year: 2014,
  },
  {
    id: "met-jou-anders",
    title: "Met jou is het anders",
    author: "Hanne Eerdekens",
    category: "Drama & Realisme",
    summary: "Een verhaal over hoe alles verandert met iemand.",
    year: 2015,
  },
  {
    id: "mistland",
    title: "Mistland",
    author: "Ludo Enckels",
    category: "Drama & Realisme",
    summary: "Een verhaal over mist en verloren wegen.",
    year: 2014,
  },
  {
    id: "jongen-zonder-naam",
    title: "Jongen zonder naam",
    author: "Betty Elias",
    category: "Drama & Realisme",
    summary: "Een jongen zonder identiteit zoekt zijn naam.",
    year: 2013,
  },
  {
    id: "10-truths-dare",
    title: "10 truths en een dare",
    author: "Ashley Elston",
    category: "Drama & Realisme",
    summary: "Een spel met waararheden en durven.",
    year: 2014,
  },
  {
    id: "waarschijnlijkheid-alles",
    title: "De waarschijnlijkheid van alles",
    author: "Sarah Everett",
    category: "Drama & Realisme",
    summary: "Een verhaal over waarschijnlijkheden.",
    year: 2015,
  },
  {
    id: "woordsmid",
    title: "De woordsmid",
    author: "Patricia Forde",
    category: "Drama & Realisme",
    summary: "Een meisje ontdekt de kracht van woorden.",
    year: 2012,
  },
  {
    id: "net",
    title: "Het net",
    author: "Frank Geleyn",
    category: "Drama & Realisme",
    summary: "Een verhaal over netten en vangsten.",
    year: 2014,
  },
  {
    id: "naar-top",
    title: "Naar de top",
    author: "Dan Gemeinhart",
    category: "Drama & Realisme",
    summary: "Een jongen klimt naar de top van een berg.",
    year: 2015,
  },
  {
    id: "enkele-reis-brugge",
    title: "Enkele reis Brugge",
    author: "Hilde E. Gerard",
    category: "Drama & Realisme",
    summary: "Een verhaal over een reis naar Brugge.",
    year: 2013,
  },
  {
    id: "koekoeksjong",
    title: "Koekoeksjong",
    author: "Hilde E. Gerard",
    category: "Drama & Realisme",
    summary: "Een verhaal over een kind dat niet thuishoort.",
    year: 2014,
  },
  {
    id: "ik-zal-wachten",
    title: "Ik zal op je wachten",
    author: "Luc Hanegreefs",
    category: "Drama & Realisme",
    summary: "Een verhaal over wachten en hoop.",
    year: 2012,
  },
  {
    id: "vreemdeling-hanegreefs",
    title: "Vreemdeling",
    author: "Luc Hanegreefs",
    category: "Drama & Realisme",
    summary: "Een verhaal over vreemdelingen.",
    year: 2013,
  },
  {
    id: "volle-maen",
    title: "Volle maen",
    author: "Luc Hanegreefs",
    category: "Drama & Realisme",
    summary: "Een verhaal onder volle maan.",
    year: 2014,
  },
  {
    id: "schaduwbroer",
    title: "Schaduwbroer",
    author: "Iris Hannema",
    category: "Drama & Realisme",
    summary: "Een jongen leeft in de schaduw van zijn broer.",
    year: 2014,
  },
  {
    id: "zeevonk",
    title: "Zeevonk",
    author: "Wendy Huyghe",
    category: "Drama & Realisme",
    summary: "Een verhaal over zee en vonken.",
    year: 2014,
  },
  {
    id: "daar-werelden-botsen",
    title: "Daar waar werelden botsen",
    author: "Danielle Jawando",
    category: "Drama & Realisme",
    summary: "Een verhaal over twee werelden die botsen.",
    year: 2015,
  },
  {
    id: "atalante",
    title: "Atalante",
    author: "Barbara Jurgens",
    category: "Drama & Realisme",
    summary: "Een verhaal over een sterke vrouw.",
    year: 2013,
  },
  {
    id: "dit-mag-niemand-weten",
    title: "Dit mag niemand weten",
    author: "Martine Kamphuis",
    category: "Drama & Realisme",
    summary: "Een geheim dat niet mag worden verteld.",
    year: 2012,
  },
  {
    id: "elektrische-vissen",
    title: "Elektrische vissen",
    author: "Susan Kreller",
    category: "Drama & Realisme",
    summary: "Een verhaal over elektrische vissen en energie.",
    year: 2014,
  },
  {
    id: "opstand",
    title: "Opstand",
    author: "Agave Kruijssen",
    category: "Drama & Realisme",
    summary: "Een verhaal over opstand en rebellie.",
    year: 2014,
  },
  {
    id: "bizar",
    title: "Bizar",
    author: "Sjoerd Kuyper",
    category: "Drama & Realisme",
    summary: "Een verhaal over bizarre situaties.",
    year: 2013,
  },
  {
    id: "wij-blijven-bij-elkaar",
    title: "Wij blijven bij elkaar",
    author: "Martine Letterie",
    category: "Drama & Realisme",
    summary: "Een verhaal over samenhang en loyaliteit.",
    year: 2013,
  },
  {
    id: "hele-verhalen-halve-soldaat",
    title: "Hele verhalen voor een halve soldaat",
    author: "Benny Lindelauf",
    category: "Drama & Realisme",
    summary: "Een verhaal over verhalen en soldaten.",
    year: 2012,
  },
  {
    id: "verre-plek-vlakbij",
    title: "Een verre plek vlakbij",
    author: "Hayley Long",
    category: "Drama & Realisme",
    summary: "Een verhaal over verre plekken dichtbij.",
    year: 2013,
  },
  {
    id: "als-vuur",
    title: "Als vuur",
    author: "Sara Lövestam",
    category: "Drama & Realisme",
    summary: "Een verhaal over vuur en passie.",
    year: 2014,
  },
  {
    id: "charlie-en-ik",
    title: "Charlie en ik",
    author: "Mark Lowery",
    category: "Drama & Realisme",
    summary: "Een verhaal over vriendschap.",
    year: 2012,
  },
  {
    id: "bijna-eindeloze-afstand",
    title: "Een bijna eindeloze afstand",
    author: "Tahereh Maf",
    category: "Drama & Realisme",
    summary: "Een verhaal over afstand en verbinding.",
    year: 2014,
  },
  {
    id: "ramp-tsjernobyl",
    title: "De ramp van Tsjernobyl",
    author: "Andy Marino",
    category: "Drama & Realisme",
    summary: "Een verhaal over de ramp van Tsjernobyl.",
    year: 2011,
  },
  {
    id: "niemandsjongen",
    title: "Niemandsjongen",
    author: "Katherine Marsh",
    category: "Drama & Realisme",
    summary: "Een jongen zonder land.",
    year: 2011,
  },
  {
    id: "geloof-me",
    title: "Geloof me",
    author: "Sophie McKenzie",
    category: "Drama & Realisme",
    summary: "Een verhaal over vertrouwen.",
    year: 2011,
  },
  {
    id: "vermist",
    title: "Vermist",
    author: "Sophie McKenzie",
    category: "Drama & Realisme",
    summary: "Een meisje is vermist.",
    year: 2012,
  },
  {
    id: "alter-ego",
    title: "Alter ego",
    author: "Marissa Meyer",
    category: "Drama & Realisme",
    summary: "Een verhaal over alter ego's.",
    year: 2011,
  },
  {
    id: "niemand-houdt-november",
    title: "Niemand houdt van November",
    author: "Antonia Michaelis",
    category: "Drama & Realisme",
    summary: "Een verhaal over november en eenzaamheid.",
    year: 2011,
  },
  {
    id: "koning-sintelwoud",
    title: "Koning van het Sintelwoud",
    author: "Jen Minkman",
    category: "Drama & Realisme",
    summary: "Een verhaal over een koning in het woud.",
    year: 2012,
  },
  {
    id: "paultje-geen-jongen",
    title: "Paultje, echt geen jongen",
    author: "Brigitte Minne / Joris Thys",
    category: "Drama & Realisme",
    summary: "Een verhaal over genderidentiteit.",
    year: 2013,
  },
  {
    id: "rommelzolder-wal",
    title: "De rommelzolder van Wal",
    author: "Brigitte Minne",
    category: "Drama & Realisme",
    summary: "Een verhaal over herinneringen in een zolder.",
    year: 2014,
  },
  {
    id: "tegenwoordig-iedereen-sorry",
    title: "Tegenwoordig heet iedereen Sorry",
    author: "Bart Moeyaert",
    category: "Drama & Realisme",
    summary: "Een verhaal over excuses.",
    year: 2013,
  },
  {
    id: "duet-valse-noten",
    title: "Duet met valse noten",
    author: "Bart Moeyaert",
    category: "Drama & Realisme",
    summary: "Een verhaal over muziek en disharmonie.",
    year: 2014,
  },
  {
    id: "bestemming-onbekend",
    title: "Bestemming onbekend",
    author: "Paul Mosier",
    category: "Drama & Realisme",
    summary: "Een reis naar een onbekende bestemming.",
    year: 2014,
  },
  {
    id: "drama-queen",
    title: "Drama Queen",
    author: "Derk Visser",
    category: "Drama & Realisme",
    summary: "Een verhaal over drama.",
    year: 2014,
  },
  {
    id: "wraak",
    title: "Wraak",
    author: "Mats Wahl",
    category: "Drama & Realisme",
    summary: "Een verhaal over wraak.",
    year: 2012,
  },
  {
    id: "raak",
    title: "Raak",
    author: "Mats Wahl",
    category: "Drama & Realisme",
    summary: "Een verhaal over raken.",
    year: 2013,
  },
  {
    id: "dood",
    title: "Dood",
    author: "Mats Wahl",
    category: "Drama & Realisme",
    summary: "Een verhaal over dood.",
    year: 2013,
  },
  {
    id: "zoek",
    title: "Zoek",
    author: "Mats Wahl",
    category: "Drama & Realisme",
    summary: "Een verhaal over zoeken.",
    year: 2014,
  },
  {
    id: "agency-scandal",
    title: "The agency for scandal",
    author: "Laura Wood",
    category: "Drama & Realisme",
    summary: "Een verhaal over schandalen.",
    year: 2015,
  },
  {
    id: "buitenspel-woodrow",
    title: "Buitenspel",
    author: "Margje Woodrow",
    category: "Drama & Realisme",
    summary: "Een verhaal over buitenspel staan.",
    year: 2014,
  },
  {
    id: "futuria",
    title: "Futuria",
    author: "Suzanne Wouda",
    category: "Drama & Realisme",
    summary: "Een verhaal over de toekomst.",
    year: 2015,
  },
  {
    id: "malak",
    title: "Malak",
    author: "Erik Wouters",
    category: "Drama & Realisme",
    summary: "Een verhaal over Malak.",
    year: 2014,
  },
  {
    id: "jongen-wereld-hield",
    title: "De jongen die van de wereld hield",
    author: "Tjibbe Veldkamp",
    category: "Drama & Realisme",
    summary: "Een jongen die van de wereld houdt.",
    year: 2014,
  },
  {
    id: "labyrint",
    title: "Labyrint",
    author: "Inge Verbruggen",
    category: "Drama & Realisme",
    summary: "Een verhaal over een labyrint.",
    year: 2013,
  },
  {
    id: "doodverklaard",
    title: "Doodverklaard",
    author: "Inge Verbruggen",
    category: "Drama & Realisme",
    summary: "Een verhaal over doodverklaring.",
    year: 2014,
  },
  {
    id: "amulet-dood",
    title: "Amulet van de dood",
    author: "Frank Verleyen",
    category: "Drama & Realisme",
    summary: "Een verhaal over een amulet.",
    year: 2012,
  },
  {
    id: "brug-glas",
    title: "Een brug van glas",
    author: "Karel Verleyen",
    category: "Drama & Realisme",
    summary: "Een fragiele brug.",
    year: 2013,
  },
  {
    id: "vuur-wraak",
    title: "Het vuur van de wraak",
    author: "Karel Verleyen",
    category: "Drama & Realisme",
    summary: "Een verhaal over wraak en vuur.",
    year: 2014,
  },
  {
    id: "niemand-ziet",
    title: "Niemand ziet het",
    author: "Dolf Verroen",
    category: "Drama & Realisme",
    summary: "Een verhaal dat niemand ziet.",
    year: 2014,
  },
  {
    id: "niet-stoppen",
    title: "Niet te stoppen",
    author: "Angie Thomas",
    category: "Drama & Realisme",
    summary: "Een verhaal over niet stoppen.",
    year: 2015,
  },
  {
    id: "uit-lucht-geplukt",
    title: "Uit de lucht geplukt of hoe Ricky de wereld redt",
    author: "Mark Tijsmans",
    category: "Drama & Realisme",
    summary: "Een jongen redt de wereld.",
    year: 2014,
  },
  {
    id: "knaap-knecht-meid-moord",
    title: "De knaap, de knecht, de meid, de moord",
    author: "Mark Tijsmans",
    category: "Drama & Realisme",
    summary: "Een verhaal over moord.",
    year: 2015,
  },
  {
    id: "dansen-diep-water",
    title: "Dansen in diep water",
    author: "Laure Van den Broeck",
    category: "Drama & Realisme",
    summary: "Een verhaal over dansen in diep water.",
    year: 2014,
  },
  {
    id: "team-mortis",
    title: "Team Mortis",
    author: "Bjorn Van den Eynde",
    category: "Drama & Realisme",
    summary: "Een team vol mysterie.",
    year: 2013,
  },
  {
    id: "beschermengel",
    title: "De beschermengel",
    author: "Bjorn Van den Eynde",
    category: "Drama & Realisme",
    summary: "Een verhaal over bescherming.",
    year: 2014,
  },
  {
    id: "stille-waters",
    title: "Stille waters",
    author: "Bjorn Van den Eynde",
    category: "Drama & Realisme",
    summary: "Een verhaal over stille wateren.",
    year: 2015,
  },
  {
    id: "huilen-maan",
    title: "Huilen naar de maan",
    author: "Gerda Van Erkel",
    category: "Drama & Realisme",
    summary: "Een verhaal over huilen.",
    year: 2013,
  },
  {
    id: "hvj",
    title: "Hvj",
    author: "Lysette Van Geel",
    category: "Drama & Realisme",
    summary: "Een mysterieus verhaal.",
    year: 2014,
  },
  {
    id: "verdronken",
    title: "Verdronken",
    author: "Gerard Van Gemert",
    category: "Drama & Realisme",
    summary: "Een verhaal over verdrinken.",
    year: 2013,
  },
  {
    id: "voorbij-sterren",
    title: "Voorbij de sterren",
    author: "Eline Vantilt",
    category: "Drama & Realisme",
    summary: "Een verhaal voorbij de sterren.",
    year: 2014,
  },
  {
    id: "omzwervingen-boek",
    title: "De omzwervingen van boek",
    author: "Melanie van de Peut",
    category: "Drama & Realisme",
    summary: "Een boek zwerft rond.",
    year: 2013,
  },
  {
    id: "leugenaar",
    title: "Leugenaar leugenaar",
    author: "Herman Van de Wijdeven",
    category: "Drama & Realisme",
    summary: "Een verhaal over leugens.",
    year: 2012,
  },
  {
    id: "julia-broer-ik",
    title: "Julia en mijn broer en ik",
    author: "Herman Van de Wijdeven",
    category: "Drama & Realisme",
    summary: "Een verhaal over Julia en broers.",
    year: 2013,
  },
  {
    id: "noorderlicht-van-praag",
    title: "Noorderlicht",
    author: "Anna Van Praag",
    category: "Drama & Realisme",
    summary: "Een verhaal over noorderlicht.",
    year: 2014,
  },
  {
    id: "zoeken-esther-benito",
    title: "Zoeken naar Esther B. en het voorval met Benito",
    author: "Do Van Ranst",
    category: "Drama & Realisme",
    summary: "Een zoektocht naar Esther.",
    year: 2013,
  },
  {
    id: "vader-levens-redden",
    title: "Mijn vader zegt dat wij levens redden",
    author: "Do Van Ranst",
    category: "Drama & Realisme",
    summary: "Een verhaal over levens redden.",
    year: 2014,
  },
  {
    id: "dagboek-chihuahua",
    title: "Dagboek van een chihuahua",
    author: "Do Van Ranst",
    category: "Drama & Realisme",
    summary: "Het dagboek van een kleine hond.",
    year: 2014,
  },
  {
    id: "supernova",
    title: "Supernova",
    author: "Do Van Ranst",
    category: "Drama & Realisme",
    summary: "Een verhaal over een supernova.",
    year: 2015,
  },
  {
    id: "moeders-gevaarlijk-messen",
    title: "Moeders zijn gevaarlijk met messen",
    author: "Do Van Ranst",
    category: "Drama & Realisme",
    summary: "Een verhaal over moeders.",
    year: 2015,
  },
  {
    id: "foto-niet-sta",
    title: "De foto waar ik niet op sta",
    author: "Do Van Ranst",
    category: "Drama & Realisme",
    summary: "Een verhaal over een foto.",
    year: 2016,
  },
  {
    id: "heerestraat-rozenlaan",
    title: "Heerestraat en Rozenlaan",
    author: "Carlie Van Tongeren",
    category: "Drama & Realisme",
    summary: "Een verhaal over twee straten.",
    year: 2014,
  },
  {
    id: "sleutelbeengebaar",
    title: "Het sleutelbeengebaar",
    author: "Hilde Van Cauteren",
    category: "Drama & Realisme",
    summary: "Een gebaar vol betekenis.",
    year: 2013,
  },
  {
    id: "als-terugkomt",
    title: "Als je terugkomt",
    author: "Rebecca Stead",
    category: "Drama & Realisme",
    summary: "Een verhaal over terugkomen.",
    year: 2015,
  },
  {
    id: "wat-justyce-doen",
    title: "Wat zou Justyce doen?",
    author: "Nic Stone",
    category: "Drama & Realisme",
    summary: "Een verhaal over keuzes.",
    year: 2015,
  },
  {
    id: "geen-beste-dag-voodoo",
    title: "Geen beste dag voor voodoo",
    author: "Jeff Strand",
    category: "Drama & Realisme",
    summary: "Een verhaal over voodoo.",
    year: 2014,
  },
  {
    id: "pestbloemen",
    title: "Pestbloemen",
    author: "Mats Strandberg",
    category: "Drama & Realisme",
    summary: "Een verhaal over pesten.",
    year: 2014,
  },
  {
    id: "zusjes-verzonken-moeras",
    title: "De zusjes uit het Verzonken Moeras",
    author: "Lucy Strange",
    category: "Drama & Realisme",
    summary: "Een verhaal over zusjes.",
    year: 2015,
  },
  {
    id: "koorddansen",
    title: "Koorddansen",
    author: "Wendy Stroobant",
    category: "Drama & Realisme",
    summary: "Een verhaal over balanceren.",
    year: 2014,
  },
  {
    id: "maar-ik-ben-jou-niet",
    title: "Maar ik ben jou niet",
    author: "Nadine Swagerman",
    category: "Drama & Realisme",
    summary: "Een verhaal over identiteit.",
    year: 2014,
  },
  {
    id: "verhalen-binnenstad",
    title: "Verhalen uit de binnenstad",
    author: "Shaun Tan",
    category: "Drama & Realisme",
    summary: "Verhalen uit de stad.",
    year: 2012,
  },
  {
    id: "match",
    title: "Match",
    author: "Buddy Tegenbosch",
    category: "Drama & Realisme",
    summary: "Een verhaal over voetbal.",
    year: 2014,
  },
  {
    id: "gewist",
    title: "Gewist",
    author: "Teri Terry",
    category: "Drama & Realisme",
    summary: "Een verhaal over uitwissen.",
    year: 2014,
  },
  {
    id: "gegijzeld",
    title: "Gegijzeld",
    author: "Chinouk Thijssen",
    category: "Drama & Realisme",
    summary: "Een verhaal over gegijzelden.",
    year: 2014,
  },
  {
    id: "nete",
    title: "Nete",
    author: "Lyne Uytterhoeven",
    category: "Drama & Realisme",
    summary: "Een verhaal over Nete.",
    year: 2014,
  },
];
